#!/usr/bin/env bash
# This script that iteration numbers from 1 to 20 and:
# displays 4 and then bad luck from China
# displays 9 and then bad luck from Japan
# displays 17 and then bad luck from Italy

j="1"
while [ $j -le 20 ]
do
	case $j in
		4)
			echo "$j"
			echo "bad luck from China"
			;;
		9)
			echo "$j"
			echo "bad luck from Japan"
			;;
		17)
			echo "$j"
			echo "bad luck from Italy"
			;;
		*)
			echo "$j"
	esac
	((j++))
done
